class Drawer():
    def draw_hangman(attempts):
        if attempts == 6:
            print ('            _______')
            print ('            |/')
            print ('            |')
            print ('            |')
            print ('            |')
            print ('            |')
            print ('            |')
            print ('          __|________')
            print ('          |         |')
        elif attempts == 5:
            print ('            _______')
            print ('            |/')
            print ('            |     ( )')
            print ('            |')
            print ('            |')
            print ('            |')
            print ('            |')
            print ('          __|________')
            print ('          |         |')
        elif attempts == 4:
            print ('            _______')
            print ('            |/')
            print ('            |     ( )')                     
            print ('            |      |')
            print ('            |')
            print ('            |')
            print ('            |')
            print ('          __|________')
            print ('          |         |')
        elif attempts == 3:
            print ('            _______')
            print ('            |/')
            print ('            |     ( )')
            print ('            |      |_')
            print ('            |        \\')
            print ('            |')
            print ('            |')
            print ('          __|________')
            print ('          |         |')
        elif attempts == 2:
            print ('            _______')
            print ('            |/')
            print ('            |     ( )')
            print ('            |     _|_')
            print ('            |    / | \\')
            print ('            |')
            print ('            |')
            print ('          __|________')
            print ('          |         |')
        elif attempts == 1:
            print ('            _______')
            print ('            |/')
            print ('            |     ( )')
            print ('            |     _|_')
            print ('            |    / | \\')
            print ('            |       \\')
            print ('            |')
            print ('          __|________')
            print ('          |         |')
        elif attempts == 0:
            print ('            _______')
            print ('            |/')
            print ('            |     ( )')
            print ('            |     _|_')
            print ('            |    / | \\')
            print ('            |     / \\')
            print ('            |')
            print ('          __|________')
            print ('          |         |')